apiVersion: v1
kind: Pod
metadata:
  name: centos-static-pod
  labels:
    app: centos
spec:
  containers:
  - name: centos-container
    image: centos
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"