apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
spec:
  selector:
    app.kubernetes.io/name: proxy
    app: httpserver
  ports:
  - name: httpserver-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc