apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - name: kube-proxy
        image: k8s.gcr.io/kube-proxy:v1.23.0
        command:
        - /usr/local/bin/kube-proxy
        args:
        - --config=/var/lib/kube-proxy/config.conf
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy-config
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-proxy-token
          readOnly: true
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      hostNetwork: true
      volumes:
      - name: kube-proxy-config
        configMap:
          name: kube-proxy
      - name: kube-proxy-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3607
              audience: api
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory