apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy
  namespace: kube-system
data:
  config.conf: |
    kind: KubeProxyConfiguration
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    mode: "ipvs"
    ipvs:
      strictARP: true
    clusterCIDR: "10.43.0.0/16"  # Update this to match your cluster's CIDR