replicaCount: 1
namespace: password-generator
image:
  repository: praveenkumar081097/password-generator
  tag: latest
  pullPolicy: Always

service:
  name: password-generator-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
    - host: pg.cluster.lab.net
      paths:
        - path: /
          pathType: Prefix
        - path: /api/
          pathType: Prefix
        - path: /healthz
          pathType: Prefix
  port: 80
